// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Roniroid.Basics.EF.CompiledModels
{
    public partial class BasicsDbContextModel
    {
        private BasicsDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("db739e2f-bbe2-425d-b6da-db7f325aebc9"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var person = PersonEntityType.Create(this);
            var user = UserEntityType.Create(this);

            UserEntityType.CreateForeignKey1(user, person);

            PersonEntityType.CreateAnnotations(person);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.3");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
