// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Roniroid.Basics.EF.CompiledModels;
using Roniroid.Basics.EF.Data;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(BasicsDbContext), typeof(BasicsDbContextModel))]
