// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Roniroid.Basics.EF.Data;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Roniroid.Basics.EF.CompiledModels
{
    [DbContext(typeof(BasicsDbContext))]
    public partial class BasicsDbContextModel : RuntimeModel
    {
        private static readonly bool _useOldBehavior31751 =
            System.AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue31751", out var enabled31751) && enabled31751;

        static BasicsDbContextModel()
        {
            var model = new BasicsDbContextModel();

            if (_useOldBehavior31751)
            {
                model.Initialize();
            }
            else
            {
                var thread = new System.Threading.Thread(RunInitialization, 10 * 1024 * 1024);
                thread.Start();
                thread.Join();

                void RunInitialization()
                {
                    model.Initialize();
                }
            }

            model.Customize();
            _instance = (BasicsDbContextModel)model.FinalizeModel();
        }

        private static BasicsDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
